name: Tests

on:
    pull_request:
    push:
        branches:
            - 'master'

jobs:
    tests:
        needs: build-matrix
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.1'
                    - '8.0'
                    - '7.4'
                    - '7.3'
                    - '7.2'
                    - '7.1'
                    - '7.0'
                    - '5.6'
        steps:
            -   uses: actions/checkout@v2.4.0
            -   uses: shivammathur/setup-php@2.16.0
                with:
                    php-version: ${{ matrix.php-version }}
                    ini-values: "memory_limit=-1, error_reporting=-1, display_errors=On"
            -   name: Install core dependencies
                uses: ramsey/composer-install@1.3.0
            -   name: Get test cloud
                run: echo "CLOUDINARY_URL=$(bash tools/get_test_cloud.sh)" >> $GITHUB_ENV
            -   name: Show test cloud
                run: echo $CLOUDINARY_URL | cut -d'@' -f2)
            -   run: vendor/bin/phpunit
